######################## default configuration ####################
baseURL = "https://messaginebot.com/"
title = "Messagine Bot"
theme = "bigspring"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-GHTWKJJ7V2" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/fontawesome/css/all.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Source Code"
URL = "https://github.com/messagine/messagine-bot"
weight = 1

# [[menu.main]]
# name = "Blog"
# URL = "blog"
# weight = 1

# [[menu.main]]
# name = "Pricing"
# URL = "pricing"
# weight = 2

[[menu.main]]
name = "Contact"
URL = "mailto:messaginebot@gmail.com"
weight = 3

# [[menu.main]]
# name = "FAQ"
# URL = "faq"
# weight = 4

[[menu.main]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 5

# footer menu left
# [[menu.footer_left]]
# name = "About Us"
# URL = "#"

# [[menu.footer_left]]
# name = "Quick Start"
# URL = "#"

# [[menu.footer_left]]
# name = "Pricing"
# URL = "pricing"


# footer menu middle
# [[menu.footer_middle]]
# name = "Pricing"
# URL = "pricing"

# [[menu.footer_middle]]
# name = "Platform"
# URL = "#"

# [[menu.footer_middle]]
# name = "Features"
# URL = "#"

# footer menu right
# [[menu.footer_right]]
# name = "Privacy Policy"
# URL = "privacy-policy"

# [[menu.footer_right]]
# name = "Terms & Conditions"
# URL = "terms-conditions"

# [[menu.footer_right]]
# name = "FAQ"
# URL = "faq"

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "200px"
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "Messagine"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

########### footer content ##########
# footer_menu_left = "Company"
# footer_menu_middle = "Product"
# footer_menu_right = "Support"
# footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
# copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "Get Started"
link = "https://t.me/MessagineBot"

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://facebook.com/messagine"

[[params.social]]
title = "instagram"
icon = "fab fa-instagram"
link = "https://instagram.com/messagine"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/messagine"

# [[params.social]]
# title = "skype"
# icon = "ti-skype"
# link = "#"

# [[params.social]]
# title = "linkedin"
# icon = "ti-linkedin"
# link = "#"